# application.yaml
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
tmdb:
  api-key: 5a7f899bf4a73482bd8b4a85274e9863
  base-url: https://api.themoviedb.org/3
cloudinary:
  cloud-name: dgxepmogx
  api-key: 381235941254148
  api-secret: -RT1DAMCr8-bdY54nfRBBgD-F4s
spring:
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:

      max-file-size: 1500MB
      max-request-size: 1500MB
  datasource:
    url: jdbc:postgresql://localhost:5433/moviedb
    username: h1eu
    password: "password"
  jpa:
    hibernate:
      ddl-auto: validate 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com        # ví dụ
    port: 587
    username: pham5446@gmail.com
    password: czulopbcpgnhfpdl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      namespace: movie:sessions   # key prefix  movie:sessions:*
      flush-mode: on-save         # (default) ghi khi session thay đổi
      save-mode: on-set-attribute # chỉ lưu field bị đổi
  security:
    oauth2:
      client:
        registration:
          # === Google ===
          google:
            client-id: "617824209981-np2qj75ut5r8ise2l0imn2olhbjqlprl.apps.googleusercontent.com"
            client-secret: "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"
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

        provider:
          # Google: chỉ cần issuer-uri (OIDC discovery)
          google:
            issuer-uri: https://accounts.google.com

app:
  jwt:
    secret: 69e09ce7aca975e391bfcbf6b6bfcbeafd747ad280a7874c0d51c86b2e59430f
    access-ttl-min: 15
    refresh-ttl-day: 7
    refresh-cookie: refresh_token
  cors:
    allowed-origins:
      - http://localhost:5173         # Vite dev
      - https://my-movie-frontend.com